### ISSUE TITLE
npm @ory/client - Objects being duplicated when calling OAuth2Api.acceptOAuth2ConsentRequest()

### ISSUE THREAD

**Issue by dannycarrera** [ory/sdk#321]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/sdk/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/sdk/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When assigning an object (such as name) to id_token and calling OAuth2Api.acceptOAuth2ConsentRequest(), the resulting localStorage value is duplicated.

### Reproducing the bug

1. Self host Ory Kratos
2. Self host Ory Hydra
3. Attach object to id_token
4. Call OAuth2Api.acceptOAuth2ConsentRequest()
5. Inspect localStorage in the browser

### Relevant log output

```shell
{  
    "profile": {
        "name": [
            {
                "first": "John",
                "last": "Doe"
            },
            {
                "first": "John",
                "last": "Doe"
            }
        ],
    },
}
```

### Relevant configuration

```yml
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Person",
    "type": "object",
    "properties": {
      "traits": {
        "type": "object",
        "properties": {
          "name":{
            "type":"object",
            "properties": {
              "first": {
                "type":"string",
                "title":"Your first name",
                "minLength": 1,
                "maxLength": 32
              },
              "last": {
                "type":"string",
                "title":"Your last name",
                "minLength": 1,
                "maxLength": 32
              }
            },
            "required": ["first","last"]
          }
        },
        "required": ["name"]
      }
    },
    "additionalProperties": false
  }
```

### Version

1.5.2

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

Binary
